### ISSUE TITLE
[Error] Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Ganariya** [studioLaCosaNostra/hexo-twitter-auto-publish#1]
Hello, I'm ganariya, student in japan!

I'd like to hexo-twitter-auto-publish.
So, I install this library and set KEYS in config.yml.

However, If I try to command `hexo deploy -g`
then this error happens.

```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'length' of undefined
    at /Users/ganariya/ganariya_blog/node_modules/hexo-twitter-auto-publish/dist/index.js:143:65
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ganariya/ganariya_blog/node_modules/hexo-twitter-auto-publish/dist/index.js:4:58)
```

I check index.js 143:65, 

```
            for (var index = 0; index < hexo.locals.cache.posts.length; index++) 
```

length is undefined.

I check the structure hexo.locals, hexo.locals.chache.posts.posts.length is correct?
(Sorry, I can not understand well js.)

Is this a bug  or should I set setting in config.yml?

Thank you.

**Comment by rayros** [comment]
Hey thanks for reporting the bug. A new hexo version came out and I missed it and changed a bit there, so it doesn't work. I have uploaded a new version 0.0.9 of the package. Please check that it works fine now. `npm i hexo-twitter-auto-publish@0.0.9`

**Comment by Ganariya** [comment]
Hello, thanks for your fix to new hexo!
I tried to install and success to post to twitter. 
Thank you.

Sorry,  and I'd like to know about one thing , so I'd like to another thread >< .
