### ISSUE TITLE
camelize function does not works in japanese or chainise or so.

### ISSUE THREAD

**Issue by Ganariya** [studioLaCosaNostra/hexo-twitter-auto-publish#3]
Hello, I came to post to twitter, Thank you very much!

I run into a problem, so I write here.

index.ts's 61~63's function `camelize` is 

```ts
const camelize = (text: string) => {
  return text.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase());
}
```
and this function will not support Japanese or Chainese or so , in twitter tag.

For example, if I use "競技プログラミング" as a tag, I get a tag as "グ" only.

Camerize's original funtion's aim is trying to make 'hello_world' -> 'helloWolrd'.
Is there a support for Japanese or Chinese or so? 
(Sorry, I can't well ts and reg expression, I'm going to study.)

**Comment by rayros** [comment]
check `npm install hexo-twitter-auto-publish@0.0.10`
